// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

export const meta = {
  user: {
    create: { type: 'mutation' },
    list: { type: 'query' },
  },
} as const;

export type Meta = typeof meta;
