// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

export const meta = {
  email: {
    sendEmail: { type: 'action' },
  },
  organization: {
    create: { auth: 'required', rateLimit: 'organization/create', type: 'mutation' },
  },
} as const;

export type Meta = typeof meta;
